#!/bin/bash
# Author: Shota Kitazawa
 
function echo_metric() {
    case $(basename $OWN_NAME) in
        "ipvsadm_weight")
        echo $1.value $WEIGHT
        ;;
        "ipvsadm_actcon")
        echo $1.value $ACTCON
        ;;
        "ipvsadm_inactcon")
        echo $1.value $INACTCON
        ;;
    esac
}

function echo_config() {
    echo "$1.label $1"
    echo "$1.draw LINE"
    case $OWN_NAME in
        ipvsadm_weight)
        echo "$1.info The weight of $1."
        ;;
        ipvsadm_actcon)
        echo "$1.info The active connection of $1."
        ;;
        ipvsadm_inactcon)
        echo "$1.info The inactive connection of $1."
        ;;
    esac
}

function main(){
    if [ "$OPTION" = "" ]; then
        for i in $ADDRESSPORT; do
            echo_metric $i 
        done
    elif [ "$OPTION" =  "config" ]; then
        for i in $ADDRESSPORT; do
            echo_config $i 
        done
    fi
}


IFS='
'
for STATE in $(ipvsadm -l | egrep "([0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]{1,5}"); do
    OWN_NAME=$0
    OPTION=$1
    ADDRESSPORT=$(echo $STATE | awk '{print $2}')
    WEIGHT=$(echo $STATE | awk '{print $4}')
    ACTCON=$(echo $STATE | awk '{print $5}')
    INACTCON=$(echo $STATE | awk '{print $6}')
    main
done

