#!/bin/bash
# Author: Shota Kitazawa

COUNT=0
 
function echo_metric() {
    case $(basename $OWN_NAME) in
        "ipvsadm_weight")
        echo $1.value $WEIGHT
        ;;
        "ipvsadm_active")
        echo $1.value $ACTIVE
	COUNT=$(expr $COUNT + $ACTIVE)
        ;;
    esac
}

function echo_config() {
    echo "$1.label $1"
    echo "$1.draw LINE"
    case $(basename $OWN_NAME) in
        ipvsadm_weight)
        echo "$1.info The weight of $1."
        ;;
        ipvsadm_active)
        echo "$1.info The active connection of $1."
        ;;
    esac
}

IFS='
'
for STATE in $(ipvsadm -l | egrep "([0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]{1,5}"); do
    OWN_NAME=$0
    OPTION=$1
    ADDRESSPORT=$(echo $STATE | awk '{print $2}')
    WEIGHT=$(echo $STATE | awk '{print $4}')
    ACTIVE=$(echo $STATE | awk '{print $5}')

    if [ "$OPTION" = "" ]; then
        for i in $ADDRESSPORT; do
            echo_metric $i 
        done
    elif [ "$OPTION" =  "config" ]; then
        for i in $ADDRESSPORT; do
            echo_config $i 
        done
    fi
done

if [ "$(basename $0)" = "ipvsadm_active" ]; then 
  if [ "$OPTION" = "config" ]; then
        echo "sum.label sum"
        echo "sum.draw STACK"
        echo "sum.colour ccff00"
        echo "sum.info Sum of the active connection."
  else
    echo "sum.value $COUNT"
  fi
fi
