#!/bin/bash
# Author: Shota Kitazawa

COUNT=0

IFS='
'
for STATE in $(ipvsadm -l | egrep "([0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]{1,5}"); do
    OWN_NAME=$0
    OPTION=$1
    ADDRESSPORT=$(echo $STATE | awk '{print $2}')
    ACTIVE=$(echo $STATE | awk '{print $5}')

    if [ "$OPTION" =  "config" ]; then
        echo "$ADDRESSPORT.label $ADDRESSPORT"
        echo "$ADDRESSPORT.draw LINE"
        echo "$ADDRESSPORT.info The active connection of $1."
    else
        echo $ADDRESSPORT.value $ACTIVE
        COUNT=$(expr $COUNT + $ACTIVE)
    fi
done

if [ "$OPTION" = "config" ]; then
    echo "sum.label sum"
    echo "sum.draw STACK"
    echo "sum.colour ccff00"
    echo "sum.info Sum of the active connection."
else
    echo "sum.value $COUNT"
fi
